#!/usr/bin/env node
// One-time migration: data/ministries.csv -> D1 (scripts/schema.sql's
// tables). Doesn't touch D1 directly — emits a SQL file for
// `wrangler d1 execute --file=` to run (--local first, then --remote),
// same as scripts/schema.sql itself. Re-runnable: regenerates the file
// from scratch each time: run it against `--local`, inspect, discard, and
// re-run as many times as needed while iterating; only run --remote once,
// against a freshly-reset (or empty) production database.
//
// Usage: node scripts/migrate-data.mjs > scripts/generated-migration.sql
// Migration report (counts, warnings) goes to stderr, not stdout, so it
// doesn't end up inside the generated SQL file.

import { readFileSync } from 'node:fs';
import { parseCsv } from '../worker/lib/csv.js';
import { parseParenList, slugify } from '../worker/lib/text.js';

const CSV_PATH = new URL('../data/ministries.csv', import.meta.url);

function sqlString(value) {
  return `'${String(value ?? '').replace(/'/g, "''")}'`;
}

function log(...args) {
  console.error(...args);
}

const csvText = readFileSync(CSV_PATH, 'utf-8');
const { rows } = parseCsv(csvText);

const sql = [];
const staffIdByName = new Map(); // first-seen home staff, by exact name
const namesBySlug = new Map(); // slug -> Set<name>, for collision detection
let nextStaffId = 1;
let staffInsertCount = 0;
let assignmentInsertCount = 0;
let unresolvedAssignments = 0;
let duplicateHomeNames = 0;

// No BEGIN TRANSACTION/COMMIT wrapper — D1's remote execution rejects raw
// transaction SQL outright ("please use the state.storage.transaction()
// ... APIs instead"), even though the local simulator tolerates it. Not
// atomic as a result, but wrangler's own file-execution already stops and
// leaves the DB unchanged if any statement in the file errors, which is
// the property that actually matters here for a one-time import.
sql.push('-- Generated by scripts/migrate-data.mjs — do not hand-edit.');

for (const row of rows) {
  const id = Number(row.id);
  const universities = JSON.stringify(
    parseParenList(row.universities).map(({ name, meta }) => ({ name, year: meta }))
  );
  const photos = JSON.stringify(
    (row.photos || '').split(';').map((s) => s.trim()).filter(Boolean)
  );
  const isDeveloping = String(row.is_developing).trim().toLowerCase() === 'true' ? 1 : 0;
  const updatedAt = row.updated_at || new Date().toISOString();

  sql.push(
    `INSERT INTO ministries (id, city, country, lat, lng, date_opened, is_developing, universities, blurb, photos, video_url, video_label, updated_at) VALUES (` +
      `${id}, ${sqlString(row.city)}, ${sqlString(row.country)}, ${Number(row.lat)}, ${Number(row.lng)}, ` +
      `${sqlString(row.date_opened)}, ${isDeveloping}, ${sqlString(universities)}, ${sqlString(row.blurb)}, ` +
      `${sqlString(photos)}, ${sqlString(row.video_url)}, ${sqlString(row.video_label)}, ${sqlString(updatedAt)});`
  );

  for (const { name, meta: role } of parseParenList(row.staff)) {
    if (staffIdByName.has(name)) {
      log(`WARNING: "${name}" appears as home staff in more than one ministry row — kept the first, ministry id ${id}'s entry ignored.`);
      duplicateHomeNames++;
      continue;
    }
    const staffId = nextStaffId++;
    staffIdByName.set(name, staffId);
    const slug = slugify(name);
    if (!namesBySlug.has(slug)) namesBySlug.set(slug, new Set());
    namesBySlug.get(slug).add(name);

    sql.push(
      `INSERT INTO staff (id, name, slug, role, home_ministry_id, updated_at) VALUES (` +
        `${staffId}, ${sqlString(name)}, ${sqlString(slug)}, ${sqlString(role)}, ${id}, ${sqlString(updatedAt)});`
    );
    staffInsertCount++;
  }
}

// Second pass — assigned_staff references home staff possibly defined in
// a row processed earlier or later, so this needs the full name->id map
// built first.
for (const row of rows) {
  const id = Number(row.id);
  const assignedNames = (row.assigned_staff || '').split(';').map((s) => s.trim()).filter(Boolean);
  for (const name of assignedNames) {
    const staffId = staffIdByName.get(name);
    if (!staffId) {
      log(`WARNING: ministry id ${id}'s assigned_staff references "${name}", which has no home entry anywhere — skipped (was already a dangling reference in the CSV).`);
      unresolvedAssignments++;
      continue;
    }
    sql.push(`INSERT INTO staff_assignments (staff_id, ministry_id) VALUES (${staffId}, ${id});`);
    assignmentInsertCount++;
  }
}

for (const [slug, names] of namesBySlug) {
  if (names.size > 1) {
    log(`WARNING: slug "${slug}" is shared by ${names.size} different names (${[...names].join(', ')}) — they'll collide on the same staff photo (images/${slug}.jpg). Pre-existing ambiguity, not introduced by this migration.`);
  }
}

const seedToken = `initial-${Date.now()}`;
sql.push(`INSERT INTO data_version (id, token, updated_at) VALUES (1, ${sqlString(seedToken)}, ${sqlString(new Date().toISOString())});`);

console.log(sql.join('\n'));

log('');
log(`Migration summary: ${rows.length} ministries, ${staffInsertCount} home staff, ${assignmentInsertCount} assignments.`);
if (duplicateHomeNames) log(`${duplicateHomeNames} duplicate home-staff name(s) — see warnings above.`);
if (unresolvedAssignments) log(`${unresolvedAssignments} unresolved assignment reference(s) — see warnings above.`);
if (!duplicateHomeNames && !unresolvedAssignments) log('No data-quality warnings.');
